title: WP Stateless
description: A WordPress plugin that uploads and serves your WordPress media from Google Cloud Storage.
logo_image: https://storage.googleapis.com/media.usabilitydynamics.com/2014/11/e5113fed-wpinvoice-plugin-icon-300x300.png
repo_url: https://github.com/wp-stateless/wp-stateless.github.io
github_url: https://github.com/wpCloud/wp-stateless
wp_link: https://wordpress.org/plugins/wp-stateless/

exclude:
  - node_modules
  - package.json
  - .idea
  - workspace.xml

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

defaults:
  - scope:
      path: "docs"
    values:
      layout: docs

branch: master